name: Release
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Docker Build
          run: DOCKER_BUILDKIT=1 docker build . -f dockerfiles/Dockerfile --output build

        - name: Get version
          id: get_version
          run: | 
              echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV 

        - name: Release
          uses: softprops/action-gh-release@v0.1.15
          with:
            tag_name: ${{ env.VERSION }}
            generate_release_notes: true
            files: |
                ./build/wart-dapp-ubuntu22